### ISSUE TITLE
Cannot start nionswift on Linux

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift-tool#2]
```
 # nionswift
Traceback (most recent call last):
  File "/home/dmuecke/Programming/anaconda3/envs/nionswift-15.1/bin/nionswift", line 10, in <module>
    sys.exit(main())
  File "/home/dmuecke/Programming/anaconda3/envs/nionswift-15.1/lib/python3.8/site-packages/nion/swift/command.py", line 68, in main
    command.launch(sys.argv)
  File "/home/dmuecke/Programming/anaconda3/envs/nionswift-15.1/lib/python3.8/site-packages/nion/nionswift_tool/command.py", line 38, in launch
    proc = subprocess.Popen([exe_path, python_prefix, "nionui_app.nionswift"] + parsed_args.args, universal_newlines=True)
  File "/home/dmuecke/Programming/anaconda3/envs/nionswift-15.1/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/dmuecke/Programming/anaconda3/envs/nionswift-15.1/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dmuecke/Programming/anaconda3/envs/nionswift-15.1/bin/NionSwiftLauncher/NionSwiftLauncher'
```

**Comment by cmeyer** [comment]
Can you recheck with latest nionswift-tool?

**Comment by Brow71189** [comment]
I just tried (on a fresh Ubuntu 20.04 VM) and the bug does not occur anymore.

However I had to run `sudo apt install libqt5gui5` before being able to start nionswift.

I installed the latest release from conda.

**Comment by cmeyer** [comment]
Closing this. `qt5-default` is required to be installed before running `nionswift-tool`. I'll update the docs to be more clear.
